name: Git Action Flow
on:
  push:
  issues: 
    types: [opened]

jobs:
  comment:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
    - name: Add funny gif
    - id: funny gif
    - with:
        GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
        comment_type: 'gif'
